on:
  push:
    branches:
    - main
    paths:
      - 'google-cloud-bigtable/**'
  pull_request:
    paths:
      - 'google-cloud-bigtable/**'
name: conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [
        { ruby: 2.6, budler: '2.4.22' },
        { ruby: 2.7, bunler: '2.4.22' },
        { ruby: 3.0, bundler: '2.5' },
        { ruby: 3.1, bundler: '2.5' },
        { ruby: 3.2, bundler: '2.5' },
        { ruby: 3.3, bundler: '2.5' },
      ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: googleapis/cloud-bigtable-clients-test
        ref: main
        path: cloud-bigtable-clients-test
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.versions.ruby }}
        bundler-cache: true
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.2'
    - run: chmod +x .kokoro/conformance.sh
    - run: gem install bundler -v ${{ matrix.versions.bundler }} 
    - run: bundle install
    - run: go version
    - run: .kokoro/conformance.sh
