on:
  push:
    branches:
    - main
    paths:
      - 'google-cloud-bigtable/**'
  pull_request:
    paths:
      - 'google-cloud-bigtable/**'
name: conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.6, 2.7, 3.0, 3.1, 3.2, 3.3 ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: googleapis/cloud-bigtable-clients-test
        ref: main
        path: cloud-bigtable-clients-test
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.node }}
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.2'
    - run: chmod +x .kokoro/conformance.sh
    - run: gem install bundler
    - run: bundle install
    - run: go version
    - run: .kokoro/conformance.sh
