on:
  push:
    branches:
    - main
    paths:
      - 'google-cloud-bigtable/**'
  pull_request:
    paths:
      - 'google-cloud-bigtable/**'
name: conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.6, 2.7, 3.0, 3.1, 3.2, 3.3 ]
        bundler: [ '2.4.22', '2.4.22', '2.5', '2.5', '2.5', '2.5' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: googleapis/cloud-bigtable-clients-test
        ref: main
        path: cloud-bigtable-clients-test
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.2'
    - run: chmod +x .kokoro/conformance.sh
    - run: gem install bundler -v ${{ matrix.bundler }} 
    - run: bundle install
    - run: go version
    - run: .kokoro/conformance.sh
